### ISSUE TITLE
DEFECT: Security Vulnerability - Unauthorized Access to User reviews / Order History

### ISSUE THREAD

**Issue by GiovaniFonseca** [Giov3ss/PowerProtein#76]
**Describe the bug**
While conducting a review in the platform's security, I identified a bug that poses a significant risk to user accounts and their associated reviews. This bug allows unauthorized users to access and edit reviews, also order history that belonging to other user's accounts. Furthermore, the bug enables users to copy links that lead directly to other user's accounts, granting unauthorized access. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in to the account.
2. Navigate to the reviews section.
3. Locate a review that belongs to a different user.
5. Copy the URL link of the user account associated with the review.
6. Open an incognito browser window or log out of the current user account.
7. Paste the copied URL link into the address bar and press Enter.

**Expected behaviour**
User accounts and their associated reviews should be segregated, preventing any unauthorized access. User should only be able to edit their own reviews and should not be able to manipulate or access other user's accounts.   

**Actual Result**
Copying and paste the URL link associated with a user's reviews, enables easy access to that user's account, the bug allows users to edit reviews that belong to other user accounts. 

**Desktop:**
- OS: Windows 10
- Browser: Chrome
- Version: N/A

**Smartphone:**
- Device: iPhone 12
- OS: iOS 14.5
- Browser: Safari
- Version: 14.1

**Comment by Giov3ss** [comment]
**Resolution Steps**

To address this issue, the following resolution steps were implemented:

I've added the following code, that checks if the username associated with the retrieved review is not equal to the username of the currently logged-in user. If the condition returns true, a warning message is displayed to the user, also render an error page 403, that stands for "Forbidden", which means the user doesn't have the necessary permissions to access a certain resource.

**EDIT REVIEWS**
````
review = get_object_or_404(Reviews, id=pk)
    if review.name != request.user.username:
        messages.warning(request, 'You can only edit your own reviews!')
        return render(request, "errors/403.html")
````

Also stands for order history code:

**ORDER HISTORY**
````
 if order.user_profile.user != request.user:
        messages.warning(request, 'You can only view your own order history!')
        return render(request, '403.html')
````
